name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["windows", "linux", "darwin"]
        goarch: ["amd64", "386"]
        exclude:
        - goos: darwin
          goarch: "386"
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      if: matrix.goos != 'windows'
      env:
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
        CGO: 0
      run: |
        mkdir -p build/${GOOS}-${GOARCH}
        go build -o build/${GOOS}-${GOARCH}/gist .
        tar czvf gist-${GOOS}-${GOARCH}.tar.gz -C build/${GOOS}-${GOARCH} gist
        
    - name: Build Windows
      if: matrix.goos == 'windows'
      env:
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
        CGO: 0
      run: |
        mkdir -p build/${GOOS}-${GOARCH}
        go build -o build/${GOOS}-${GOARCH}/gist.exe .
        zip -j gist-${GOOS}-${GOARCH}.zip build/${GOOS}-${GOARCH}/gist.exe
